title: Bill Farmer # your name (or website title) here
logo: "/images/binary1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer first and in heart. Vice President of Engineering 'and all things related to technology' for @ClarityBizSol. 
  Executive and engineer who helps develop the short- and long-term technology direction of the organization and utilizes capital investments
  in research and development (R&D) and technology needs to help the organization reach its objectives. Team First.
  <br>
  "Data is the sword of the 21st century, those who wield it well, the Samurai." - Jonathan Rosenberg, adviser to Larry Page and former SVP of products at Google
  <br><br>
  Family. The most important thing. 
  <br><br>
  <a href="https://www.linkedin.com/in/william-farmer-34a9813">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
